Transform: AWS::Serverless-2016-10-31

Parameters:
  GithubUserSession:
    Type: String
    NoEcho: true
  GithubApiToken:
    Type: String
    NoEcho: true

Resources:
  GithubSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      SecretString: !Sub '{"UserSession": "${GithubUserSession}", "ApiToken": "${GithubApiToken}"}'

  Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: api
      AutoPublishAlias: live
      Runtime: go1.x
      CodeUri: ./api/api
      Timeout: 20
      MemorySize: 512
      Environment:
        Variables:
          GITHUB_USER_SESSION: !Sub "{aws-sm}${GithubSecret}::UserSession"
          GITHUB_API_TOKEN: !Sub "{aws-sm}${GithubSecret}::ApiToken"
          PERMITTED_GITHUB_ORG: glassechidna
          TAGS_JMESPATH: |
            {
                "github:jobId":  to_string(job.id),
                "github:runId":  to_string(run.id),
                "github:run":    to_string(run.run_number),
                "github:job":    job.name,
                "github:commit": run.head_commit.id,
                "github:repo":   run.repository.full_name,
                "github:author": run.head_commit.author.email
            }
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref GithubSecret
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - sts:AssumeRole
                - sts:TagSession
              Resource: "*"
              Condition:
                ForAllValues:StringLike:
                  # only allow this lambda to pass github:* session tags
                  aws:TagKeys: "github:*"
                StringEquals:
                  # only allow github actions to assume roles that have a `github:actions-role=true` tag
                  aws:ResourceTag/github:actions-role: true
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            TimeoutInMillis: 20000
            PayloadFormatVersion: "1.0"

  ExampleRoleForGithub:
    Type: AWS::IAM::Role
    Properties:
      Tags:
        - Key: github:actions-role
          Value: true
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: sts:AssumeRole
            Condition:
              ForAllValues:StringLike:
                aws:TagKeys: "github:*"
              StringEquals:
                aws:PrincipalArn: !GetAtt FunctionRole.Arn # auto-generated by AWS SAM by appending `Role` to function resource
          - Effect: Allow
            Principal:
              AWS: !GetAtt FunctionRole.Arn
            Action: sts:TagSession
      Policies:
        - PolicyName: AllowStuff
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: iam:ListAccountAliases
                Resource: "*"

Outputs:
  GithubSecret:
    Value: !Ref GithubSecret
  Url:
    Value: !Sub https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/
  Function:
    Value: !Ref Function.Version
  ExampleRoleForGithub:
    Value: !GetAtt ExampleRoleForGithub.Arn

